type User {
  id: ID!
  name: String!
  email: String!
  password: String!
  todos: [Todo!]!
}
enum StatusResult {
  SUCCESS
  FAILURE
}
type ResponseStatus {
  status: StatusResult!
}

input NewUser {
  name: String!
  email: String!
  password: String!
}

extend type Query {
  getAllUsers: [User!]!
}

extend type Mutation {
  createUser(input: NewUser!): ResponseStatus!
}
