package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	graphql1 "github.com/nagisa599/go-graphql-template/graphql"
	graphql_model "github.com/nagisa599/go-graphql-template/graphql/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input graphql_model.NewUser) (*graphql_model.ResponseStatus, error) {
	response, err := r.UserHandler.CreateUser(ctx, input)
	if err != nil {
		return nil, err
	}
	return response, nil
}

// GetAllUsers is the resolver for the getAllUsers field.
func (r *queryResolver) GetAllUsers(ctx context.Context) ([]*graphql_model.User, error) {
	response, err := r.UserHandler.GetAllUsers(ctx)
	if err != nil {
		return nil, err
	}
	return response, nil
}

// Todos is the cv resolver for the todos field.
func (r *userResolver) Todos(ctx context.Context, obj *graphql_model.User) ([]*graphql_model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// User returns graphql1.UserResolver implementation.
func (r *Resolver) User() graphql1.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
